CREATE TABLE MEMBER (
  CUSTOMER_NO VARCHAR(10) NOT NULL,
  KANJI_FAMILY_NAME VARCHAR(10) NOT NULL,
  KANJI_GIVEN_NAME VARCHAR(10) NOT NULL,
  KANA_FAMILY_NAME VARCHAR(10) NOT NULL,
  KANA_GIVEN_NAME VARCHAR(10) NOT NULL,
  BIRTHDAY DATE NOT NULL,
  GENDER VARCHAR(1) NOT NULL,
  TEL VARCHAR(13) NOT NULL,
  ZIP_CODE VARCHAR(7) NOT NULL,
  ADDRESS VARCHAR(60) NOT NULL,
  MAIL VARCHAR(256) NOT NULL,
  CREDIT_NO VARCHAR(16) NOT NULL,
  CREDIT_TYPE_CD VARCHAR(3) NOT NULL,
  CREDIT_TERM VARCHAR(5) NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (CUSTOMER_NO);


CREATE TABLE CREDIT_TYPE (
  CREDIT_TYPE_CD VARCHAR(3) NOT NULL,
  CREDIT_FIRM VARCHAR(80) NOT NULL,
  DISPLAY_ORDER INT NOT NULL UNIQUE
);

ALTER TABLE CREDIT_TYPE ADD CONSTRAINT PK_CREDIT_TYPE PRIMARY KEY (CREDIT_TYPE_CD);

ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_1 FOREIGN KEY (CREDIT_TYPE_CD) REFERENCES CREDIT_TYPE (CREDIT_TYPE_CD);

CREATE SEQUENCE SQ_MEMBER_1 MINVALUE 1 MAXVALUE 9999999999 CYCLE;
